<Project Sdk="Microsoft.NET.Sdk.Worker">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>dotnet-Storage_Service-92f453c2-663e-43ea-927b-0dbcf1baf331</UserSecretsId>
    <RootNamespace>Storage_Service</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="EVA_ECS.Chat.Contracts" Version="1.0.1" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="8.3.6" />
    <PackageReference Include="Microsoft.Extensions.Hosting" Version="8.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Storage-Service.Tests\**\*.cs" />
  </ItemGroup>
</Project>
